name: reusable-test

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string

jobs:
  test:
    permissions:
      contents: write
      issues: write
    runs-on: [self-hosted, macOS]
    steps:
      - run: echo "hi ${{ inputs.scheme }}"
